// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class DefaultSuite {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void SeleniumHQTest() {
    driver.get("https://www.seleniumhq.org//");
    driver.findElement(By.linkText("About")).click();
    driver.findElement(By.cssSelector("h3:nth-child(3) > a")).click();
    driver.findElement(By.linkText("Selenium IDE Is Dead, Long Live Selenium IDE!")).click();
    driver.findElement(By.id("comments")).click();
    assertThat(driver.getTitle(), is("Selenium IDE Is Dead, Long Live Selenium IDE! | Official Selenium Blog"));
    assertThat(driver.findElement(By.linkText("Official Selenium Blog")).getText(), is("Official Selenium Blog"));
  }
  @Test
  public void FailedLoginAttempt() {
    driver.get("https://login.yahoo.com/");
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("invalid");
    driver.findElement(By.id("login-signin")).click();
    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("Niestety nie rozpoznajemy tego adresu e-mail."));
  }
}
